# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Pred <- function(X, U, predict_t, phi, p, psi, q, tau1, S1, r1, tau2, S2, r2, gamma, W) {
    .Call(`_tsms_Pred`, X, U, predict_t, phi, p, psi, q, tau1, S1, r1, tau2, S2, r2, gamma, W)
}

fit <- function(X, U, beta, p, q, S1, r1, S2, r2, W) {
    .Call(`_tsms_fit`, X, U, beta, p, q, S1, r1, S2, r2, W)
}

grad <- function(X, U, beta, p, q, S1, r1, S2, r2, W) {
    .Call(`_tsms_grad`, X, U, beta, p, q, S1, r1, S2, r2, W)
}

likeli <- function(X, U, phi, p, psi, q, tau1, S1, r1, tau2, S2, r2, gamma, W, sigma) {
    .Call(`_tsms_likeli`, X, U, phi, p, psi, q, tau1, S1, r1, tau2, S2, r2, gamma, W, sigma)
}

